volha: homework 13
eugene-okulik/st6 pull request #108
Opened 2024-03-04 16:41 UTC by akidera

2024-03-04 20:39 UTC, eugene-okulik requested changes

2024-03-04 20:39 UTC, eugene-okulik commented on homework/volha_pikulenka/homework13/task.py
> +            print('Sunday')
Этот велосипед уже изобрели до нас )))
```python
some_date.strftime('%A')
```

2024-03-05 06:12 UTC, akidera commented on homework/volha_pikulenka/homework13/task.py
> +            print('Sunday')
согласна, чот погорячилась

2024-03-05 08:34 UTC, eugene-okulik approved these changes

2024-03-05 08:34 UTC, merged