oksana: homework 14 completed
eugene-okulik/st6 pull request #112
Opened 2024-03-07 15:53 UTC by OksanaGavrush

2024-03-07 19:54 UTC, eugene-okulik requested changes
Ты забыл добавить студента в группу

2024-03-08 06:42 UTC, OksanaGavrush commented
Исправила

2024-03-08 11:56 UTC, eugene-okulik approved these changes

2024-03-08 11:56 UTC, eugene-okulik commented on homework/oksana_gavrush/homework_14/task.txt
> +UPDATE students SET group_id=6 WHERE name='Leos' AND second_name ='Smith';
В таких случаях лучше обращаться к записи по id, ведь в базе данных могут быть и тёзки. Т.е. было бы WHERE id = 73 вместо WHERE name='Leos' AND second_name ='Smith'

2024-03-08 11:56 UTC, merged