vasiliy_kuklin_hw_14
eugene-okulik/st6 pull request #125
Opened 2024-03-16 17:09 UTC by brozzz1999

2024-03-18 09:21 UTC, eugene-okulik requested changes
Нужно везде, где нужен id указывать айди того, что нужно. Получение этого id налету может вернуть тебе не тот результат, на который ты расчитывал.

2024-03-18 09:21 UTC, eugene-okulik commented on homework/vasiliy_kuklin/homework_14/lesson14.sql
> +UPDATE students  SET group_id  = (SELECT id FROM `groups` WHERE title = 'Aria' ) WHERE name = 'Mark'
Ты этим всех Марков из базы данных поместил в одну группу. А нужно поместить туда только того студента, которого создал. И если групп с названием Aria вдруг окажется больше одной, твой запрос вообще не сможет отработать.

2024-03-18 09:21 UTC, eugene-okulik commented on homework/vasiliy_kuklin/homework_14/lesson14.sql
> +INSERT INTO lessons (title, subject_id) VALUES ('Zanyatie one', (SELECT id FROM subjets WHERE title = 'Geodezika'))
Получать id таким способом - очень ненадежно. Название предмета не является уникальным полем в базе данных. По логике двух предметов с одним названием быть не может, но всякое случается.
Когда ты инсертишь так, руками, то айди того, что инстертнулось, ты можешь посмотреть в базе руками. Когда ты это будешь делать из python, там тоже есть возможность узнать id того, что инсертнулось.

2024-03-19 17:00 UTC, brozzz1999 commented on homework/vasiliy_kuklin/homework_14/lesson14.sql
> +INSERT INTO lessons (title, subject_id) VALUES ('Zanyatie one', (SELECT id FROM subjets WHERE title = 'Geodezika'))
Тогда не понимаю каким образом получить id если в таблице subjets не к чему привязать запрос(там две колонки id и title)

2024-03-19 17:08 UTC, eugene-okulik commented on homework/vasiliy_kuklin/homework_14/lesson14.sql
> +INSERT INTO lessons (title, subject_id) VALUES ('Zanyatie one', (SELECT id FROM subjets WHERE title = 'Geodezika'))
Ладно, я этим заданием, с большего готовил к следующим заданиям, где всё питоном нужно делать. Здесь загвоздка в том, что селект тебе вернет один и более результатов и у тебя не будет стопроцентно правильного id.  
Но и руками если такое делается, то правильный id ищется просто в базе глазами. Можно подключить к этому какой-то селект, но в итоге из всех вариантов нужно будет глазами выбрать. И нужный id вставить в следующие запросы. Прям сам id вставить, потому что только по id мы можем уникально обратиться к записи.

2024-03-19 17:08 UTC, eugene-okulik approved these changes
Короче, пойдем в 15 разбираться. Там интереснее.

2024-04-08 09:12 UTC, merged