volha: homework 17
eugene-okulik/st6 pull request #132
Opened 2024-03-21 13:26 UTC by akidera

2024-03-22 07:08 UTC, eugene-okulik requested changes
Круто. Вижу сильно заморочилась с тем, чтобы разделить на слова не только по пробелам.  
Но сейчас еще есть одна проблемка: если искать по слову, которое является частью слова, например, искать не по слову WARN, а по слову ARN, то программа падает с `ValueError: 'ARN' is not in list`

2024-03-25 20:53 UTC, akidera commented
сделала по тупому. не могу придумать решение для своего способа.
и новое решение в голову пока не приходит

2024-03-26 07:41 UTC, eugene-okulik commented
> сделала по тупому. не могу придумать решение для своего способа. и новое решение в голову пока не приходит

Смотри, у тебя, как у программиста, всегда есть вариант забить на решение какого-то специфического кейса. Но, что обязательно сделать, так это чтобы программа не падала с эксепшеном. Можно в такой ситуации просто сказать юзеру, что "слово не найдено" ))

2024-03-26 07:43 UTC, eugene-okulik approved these changes
Ну ладно, сойдет, хоть ты и распечатываешь не 5 слов вокруг, а 50 символов вокруг.

2024-03-26 07:44 UTC, merged