oksana: homework_18_completed
eugene-okulik/st6 pull request #143
Opened 2024-03-29 07:31 UTC by OksanaGavrush

2024-03-29 08:36 UTC, eugene-okulik requested changes

2024-03-29 08:36 UTC, eugene-okulik commented on homework/oksana_gavrush/homework_18/task.py
> +}
У тебя сдесь отступы по 3 или 6 символов. И Линту это не нравится. Нужно сделать по 4 и 8

2024-03-29 08:36 UTC, eugene-okulik commented on homework/oksana_gavrush/homework_18/task.py
> +   "name": "Apple MacBook Pro 18"}
И здесь тоже отступ 3 пробела вместо четырех.

2024-03-29 08:36 UTC, eugene-okulik commented
Осталось поправить то, на что Линт ругается и всё будет круто

2024-03-29 09:43 UTC, OksanaGavrush commented
исправила, спасибо!

2024-03-30 07:46 UTC, eugene-okulik approved these changes

2024-03-30 07:47 UTC, merged