Aleksandr Tsvetkov: homework 19
eugene-okulik/st6 pull request #145
Opened 2024-03-31 12:58 UTC by Aliaksandr11

2024-03-31 17:24 UTC, eugene-okulik requested changes
Всё ок. Но вот захотелось завалить одной штучкой ))))

2024-03-31 17:24 UTC, eugene-okulik commented on homework/aleksandr_tsvetkov/homework_19/test_api.py
> +        'The values dont match'
Я чисто, чтобы завалить: напиши don't правильно, но одинарные кавычки вокруг текста не меняй на двойные

2024-03-31 17:24 UTC, eugene-okulik commented on homework/aleksandr_tsvetkov/homework_19/test_api.py
> +    assert response.status_code == 404, 'Object still exists after deletion'
:+1:

2024-03-31 18:31 UTC, Aliaksandr11 commented
Даже не знал, что есть какие-то способы сделать это без двойных кавычек, интересно было узнать, что они есть)

2024-04-01 07:40 UTC, eugene-okulik approved these changes
:+1:   
Ну это я так, чтобы ты вспомнил как такое делается. А то вдруг забыл ))

2024-04-01 07:40 UTC, merged