ekaterina_klimova_Analyzer_harder_version
eugene-okulik/st6 pull request #158
Opened 2024-04-07 10:24 UTC by KaterinaSergeevna

2024-04-08 09:10 UTC, eugene-okulik requested changes
Хорошо бы поправить подход с путём к одному файлу. Сейчас даже если я изменю твой хардкод `"\\"` на `"/"`, у меня не работает:
```
python analyzer_h.py /home/eugene/projects/st6/homework/eugene_okulik/data/logs/rpe-api-error.2022-02-03.7.log --text WARN --unwanted answer
Text to search: WARN
Unwanted text: answer
Traceback (most recent call last):
  File "/home/eugene/projects/st6/homework/ekaterina_klimova/analyzer/analyzer_h.py", line 161, in <module>
    display_result(path, text, date, unwanted)
  File "/home/eugene/projects/st6/homework/ekaterina_klimova/analyzer/analyzer_h.py", line 146, in display_result
    res, count_block, count_res = open_and_find(path, text, date, unwanted)
  File "/home/eugene/projects/st6/homework/ekaterina_klimova/analyzer/analyzer_h.py", line 110, in open_and_find
    new_block = open_and_parse_to_blocks(file)
  File "/home/eugene/projects/st6/homework/ekaterina_klimova/analyzer/analyzer_h.py", line 57, in open_and_parse_to_blocks
    with open(path_to_file, 'r', encoding='utf-8') as open_file:
IsADirectoryError: [Errno 21] Is a directory: '/'
```
Но там прикол в том, что фиксится это чуть ли не просто удалением кода (ну и чуть-чуть добавлением). Там просто нужно перестать заморачиваться путем к файлу, мы просто пользуемся тем, что дал пользователь.  
Если починить код для этого кейса и при запуске добавить `--full`, то результат не меняется - отображается не весь блок.

2024-04-08 09:10 UTC, eugene-okulik commented on homework/ekaterina_klimova/analyzer/analyzer_h.py
> +        founded_text = {key: value for key, value in blocks.items() if unwanted in value}
Можно было перевернуть (добавить `not`) это условие и тогда в том месте, где ты вызываешь этот unwanted не пришлось бы делать удаление.
```python
elif unwanted:
    founded_text = {key: value for key, value in blocks.items() if unwanted not in value}
```

2024-04-10 10:24 UTC, KaterinaSergeevna commented on homework/ekaterina_klimova/analyzer/analyzer_h.py
> +        files = current_directory + '\\' + path
поправила поиск. Не должен падать

2024-04-10 10:24 UTC, KaterinaSergeevna commented on homework/ekaterina_klimova/analyzer/analyzer_h.py
> +                if datetime.strptime(line[:23].strip(), '%Y-%m-%d %H:%M:%S.%f'):
удалила и правда работает без изменений)

2024-04-10 10:25 UTC, KaterinaSergeevna commented on homework/ekaterina_klimova/analyzer/analyzer_h.py
> +        founded_text = {key: value for key, value in blocks.items() if unwanted in value}
вот в том то и фишка, что с not  у меня работает некорректно. Я долго билась и пошла обходным путем через удаление. Причину так и не поняла, почему не исключаются блоки

2024-04-11 14:31 UTC, eugene-okulik requested changes
Поправить нужно только этот список.  
Перед тем как вносить изменения, сделай git pull этой ветки, а то там были конфликты и после твоего коммита есть еще один, который чинит конфликты.

2024-04-11 14:31 UTC, eugene-okulik commented on homework/ekaterina_klimova/analyzer/analyzer_h.py
> +        files = path
У тебя дальше код работает расчитывая, что из этой функции вернется список файлов. В ситуации, когда пользователь указал путь к одному файлу, тебе просто нужно вернуть список из одного файла. Для этого вокруг path нужно поставить квадратные скобочки
```python
files = [path]
```

2024-04-15 09:39 UTC, eugene-okulik approved these changes

2024-04-15 09:39 UTC, merged