homework_3 done
eugene-okulik/st6 pull request #33
Opened 2024-01-28 17:22 UTC by brozzz1999

2024-01-29 09:45 UTC, eugene-okulik requested changes
Посмотри как можно это реализовать правильнее.  
Ну и поправь то, на что ругается Lint

2024-01-29 09:45 UTC, eugene-okulik commented on homework/vasiliy_kuklin/homework_3/lesson3.py
> +print(sum_price is price)
Это сравнение никогда не будет `True`  
Во-первых, если бы сравнивались значения, то sum_price будет равен price только если money = 0. То есть если такое условие сработает, то ответ будет неверный  
Во-вторых, у тебя не сравнение значений, а проверка идентичности, а разница price и money никогда не будет одним и тем же с price. Это могут быть одинаковые числа, но они не будут храниться в одной и той же ячейке памяти. Проверка идентичности для чисел применяется в очень редких, специфических случаях.  
Здесь у тебя должно быть сравнение цены с деньгами пользователя. Если денег у него больше или равно цене, то результатом этого сравнения будет `True`, иначе результатом будет `False`

2024-01-29 15:27 UTC, brozzz1999 commented on homework/vasiliy_kuklin/homework_3/lesson3.py
> +print(sum_price is price)
я знаю как написать с if, без if не понял.

2024-01-30 07:42 UTC, eugene-okulik commented on homework/vasiliy_kuklin/homework_3/lesson3.py
> +print(sum_price is price)
Но ты же написал без if

2024-01-30 07:42 UTC, eugene-okulik approved these changes

2024-01-30 07:42 UTC, merged