oksana: homework 4 completed
eugene-okulik/st6 pull request #35
Opened 2024-01-29 07:09 UTC by OksanaGavrush

2024-01-29 10:19 UTC, eugene-okulik requested changes
Всё правильно 👍 
Но одну проверку на внимательность не прошла ))

2024-01-29 10:19 UTC, eugene-okulik commented on homework/oksana_gavrush/homework_4/task_1.py
> +type_difference['dict']['i am a tuple'] = ('27.01.2024',)
В задании было

> добавьте элемент с ключом ('i am a tuple',) и любым значением

А ты выполнила как если бы там было

> добавьте элемент с ключом 'i am a tuple' и любым значением

2024-01-29 15:57 UTC, OksanaGavrush commented on homework/oksana_gavrush/homework_4/task_1.py
> +type_difference['dict']['i am a tuple'] = ('27.01.2024',)
Исправила

2024-01-30 07:43 UTC, eugene-okulik approved these changes

2024-01-30 07:43 UTC, merged