alexs: homework4 done
eugene-okulik/st6 pull request #40
Opened 2024-01-31 20:23 UTC by serebryanskijas

2024-02-01 12:34 UTC, eugene-okulik requested changes
Всё отлично. Но проверку на внимательность не прошел )))

2024-02-01 12:34 UTC, eugene-okulik commented on homework/alex_serebryansky/homework4/Task1.py
> +my_dict['dict']['i am a tuple'] = (5, 'six')
В задании было

> добавьте элемент с ключом ('i am a tuple',) и любым значением

А ты выполнил так, как если бы там было

> добавьте элемент с ключом 'i am a tuple' и любым значением

Само название этого ключа - подсказка чем он должен быть ))

2024-02-01 12:42 UTC, serebryanskijas commented on homework/alex_serebryansky/homework4/Task1.py
> +my_dict['dict']['i am a tuple'] = (5, 'six')
Это просто некоретктно составлено тех.требование или оно не полное, или двусмысленное))) 
Сейчас поправлю)

2024-02-02 15:03 UTC, eugene-okulik commented on homework/alex_serebryansky/homework4/Task1.py
> +my_dict['dict']['i am a tuple'] = (5, 'six')
Да ладно тебе! Это называется "подвох" )))

2024-02-02 15:04 UTC, eugene-okulik approved these changes

2024-02-02 15:04 UTC, merged