oksana: homework 5 completed
eugene-okulik/st6 pull request #44
Opened 2024-02-01 18:03 UTC by OksanaGavrush

2024-02-02 15:19 UTC, eugene-okulik requested changes

2024-02-02 15:19 UTC, eugene-okulik commented on homework/oksana_gavrush/homework_5/task_2.py
> +        print(num)
Вместо числа 15 у тебя сейчас Fuzz, а должно быть FuzzBuzz, так как это число кратно и трем и пяти.  
Подсказка: нужно поиграться с порядком условий.

2024-02-02 16:03 UTC, OksanaGavrush commented on homework/oksana_gavrush/homework_5/task_2.py
> +        print(num)
Спасибо, исправила.

2024-02-03 07:47 UTC, eugene-okulik approved these changes

2024-02-03 07:47 UTC, merged