oksana: homework 7 completed
eugene-okulik/st6 pull request #62
Opened 2024-02-08 16:16 UTC by OksanaGavrush

2024-02-09 08:52 UTC, eugene-okulik requested changes

2024-02-09 08:52 UTC, eugene-okulik commented on homework/oksana_gavrush/homework_7/task.py
> +    numbers.append(i)
Суть использования генераторов в том, что огромный объем информации никогда не хранится в одной переменной. Генератор возвращает по одному числу за раз. Превращение результата работы генератора в список - это то, чего делать не нужно. Более того, последовательность - это вещь бесконечная. У тебя почему-то не бесконечная. Твое генератор ограничен. А если бы он был действительно генератором последовательности, то ты бы не смогла превратить его результат в список.  
В общем, с генераторами работают не превращая их в список. Ты обращаешься к каждому элементу генератора и считаешь обращения. И благодаря счетчику, понимаешь какую цифру нужно распечатать.

2024-02-10 15:59 UTC, OksanaGavrush commented on homework/oksana_gavrush/homework_7/task.py
> +    numbers.append(i)
Исправила, спасибо!

2024-02-11 07:34 UTC, eugene-okulik approved these changes

2024-02-11 07:34 UTC, merged