volha: homework9
eugene-okulik/st6 pull request #76
Opened 2024-02-14 16:20 UTC by akidera

2024-02-16 12:45 UTC, akidera commented
самое интересное я реализовала именно так, как ты дописал в __Если есть время и желание__ 
изначальную реализацию с таким запуском example('print me', count=2) не  сделала) докину

2024-02-17 10:43 UTC, eugene-okulik commented
> самое интересное я реализовала именно так, как ты дописал в **Если есть время и желание** изначальную реализацию с таким запуском example('print me', count=2) не сделала) докину

Ок, жду

2024-02-18 08:22 UTC, akidera commented
готово

2024-02-18 12:10 UTC, eugene-okulik requested changes

2024-02-18 12:10 UTC, eugene-okulik commented on homework/volha_pikulenka/homework9/task2-2.py
> +    def wrapper(*args, count=''):
Таким оформлением (задан дефолт для count) ты говоришь, что можно всё запустить не указывая count. Но если его не указать, то значением его будет пустая строка и код `for _ in range(count)` не сможет отработать, так как range не принимает строки.  
В общем, сейчас если запустить так:
```python
example('print me')
```
то всё упадёт, но оформлено у тебя так, что такой запуск допустим. Нужно подставить какой-то другой дефолт.

2024-02-19 09:52 UTC, akidera commented on homework/volha_pikulenka/homework9/task2-2.py
> +    def wrapper(*args, count=''):
пофиксила

2024-02-20 07:42 UTC, eugene-okulik approved these changes

2024-02-20 07:42 UTC, merged